language: java
sudo: required

env:
  global:
    - secure: "nKPfH7Ppd7dnmlDBhuz/3/ocq8tJDmUIMDtSgWQzIuC9V6VyWjQN8xduesbWO+UXJNttiWCMkJWW3VDU0CqWo5/zUeOilzdz1KVja5eGKhwZGFt2pta7F6aN5xlPpJOLFne3oGpbFtAwvUSK0a5XveP4Z6WRiuOI6FGeJTOS6O+P81cykhwfG/wGXVBlJ9Q7so7EWRjkz/9O+K+Oadc+y1uzPufGn4K5huUO4pYoYktYSyr2rlwN7qEGMkwCeR2Wy6DaKp2gNfM9T28WHBayOQY/EyRWm6O9rjqQ4s7H/WTfakh8qSXeWVoZSDz81pmbwSP3K011rfhrXBil5y4LBVvXb18eyWZxjusu8poG/+bhnS370wV9FjIrYbv7Vs3lY5JrhMms9BMVyC4NpjX+TDngNIYk9f8n7xFvbcQB30U2AfgHS4mADrdvc4uR3H58EYgThPXgp5MqKkBadXZT05kNqpQTDCuGW1Q7pwyHu5yqdqp7nR+0r3DXF3ZdBTobNq7X4KafC9l9DE4/CWS/vWw1Z29LlhZXf1qpKate2EzSDKZZ2SzqQAs+wiov4voNcVI1+ZrD4kw1tP+/4NizGj1uaigQBaGI6RXDrQjb5gp6/1nrYFTc7ozYcFqtR0glIbnPr3LHlzSYVFSqp1RNDuOsCTQxewBNekDLiuUwGtc="
    - secure: "1b6XDPMpWj3CugYNvEDxzAYGR9viSKWK9eN3jvBvaOh6YZgZLvnUI+Oia5+Jbodp9xbackrvLRWFG5oN00BaRot3ZBg8lnRK0+mT7XjGYXGeAr1803e94RyTvdnFL/HBocuVDml2jWtHefCwy9W+vdNZunvrwddKb6ped+HmiiPV56pPwL4sYVuJyfyg7hTarrpgxRSha3JN9iOjca18OgvCg3BKk1tMouHwO8a5YlHVjMqCBkNXxZh8c4SJdIAd82F3L/y0mByO41IrLqoVWW6lp1jfWn0GV+gMsSVidnXYn5lnHZTAbDxi8MCn9ENI2n+b+TOFOTaHykGbCjpNCxcy0ycqTxNW8/xOF3hO9kY58opAstj6GdHTfdGLS1fHrZZp8i3ZEW6oZD915HP1lJ/E9LQUy0PFZrMBiWdbPQegaQ2Aj74ZID3xnzz1KQj0/vjK3hIN8FJ04pHKa1fLUGb+Ha9owywQrF/qVVAHVFC6X3/G0tL6DMJSqUlVHGW5/SfAI0wcvrkd/snFGLT7u1zrYbJi7chrAW+q66NIMSvNRQaAttkhxiPq6vnkYbQQIrHDrWNjcR1VYRpIatAwdTvpmF+Lwjrvmdm6nCNjbRGrMglyzenfbvO5sdG6cACkKarDkSgB9JcUs1zCgtiUvO84jXETbzdVWEcEB5W9NO0="
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
script:
- mvn clean package -DargLine="-DCosmosDBEndpoint=$CosmosDBEndpoint -DCosmosDBKey=$CosmosDBKey"
